version: '3'
services:
  app:
    image: "app"
    container_name: app
    depends_on:
    - db
    environment:
    - DB_USER=root
    - DB_PASSWORD=root
    - DB_CONNECTION_URL=jdbc:mysql://db:3306/alertbot?serverTimezone=GMT%2B3&useAffectedRows=true&useUnicode=true&serverEncoding=utf8&autoReconnect=true
    - MYSQL_CONNECTION_URL=jdbc:mysql://db:3306/
  db:
    image: "mysql:latest"
    container_name: db
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
